services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgresdb-dev
    environment:
      POSTGRES_DB: ${BACKEND_POSTGRES_DB}
      POSTGRES_USER: ${BACKEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BACKEND_POSTGRES_PASSWORD}
    ports:
      - "${BACKEND_POSTGRES_PORT}:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - pgnetwork
  redis-db:
      image: redis:7-alpine
      container_name: redisdb-dev
      ports:
        - "6379:6379"
      volumes:
        - redis-data-dev:/data
      networks:
        - pgnetwork

