services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgresdb-dev
    environment:
      POSTGRES_DB: ${BACKEND_POSTGRES_DB}
      POSTGRES_USER: ${BACKEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BACKEND_POSTGRES_PASSWORD}
    ports:
      - "${BACKEND_POSTGRES_PORT}:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - pgnetwork
  redis-db:
      image: redis:7-alpine
      container_name: redisdb-dev
      ports:
        - "6379:6379"
      volumes:
        - redis-data-dev:/data
      networks:
        - pgnetwork
  backend:
    build:
      context: ./backend
      target: development
    container_name: backend-dev
    env_file:
      - ./backend/.env
    command: sh -c "npx prisma db push --accept-data-loss && npm run dev"
    ports:
      - "3001:3001"
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - /app/node_modules
    depends_on:
      - postgres-db
      - redis-db
    networks:
      - pgnetwork

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: frontend-dev
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_API_BASE: http://localhost:3001/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    depends_on:
      - backend
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge

volumes:
  postgres-data-dev:
    driver: local
  redis-data-dev:
    driver: local
