services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgresdb-dev
    environment:
      POSTGRES_DB: ${BACKEND_POSTGRES_DB}
      POSTGRES_USER: ${BACKEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BACKEND_POSTGRES_PASSWORD}
    ports:
      - "${BACKEND_POSTGRES_PORT}:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - pgnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BACKEND_POSTGRES_USER} -d ${BACKEND_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis-db:
    image: redis:7-alpine
    container_name: redisdb-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data
    networks:
      - pgnetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  pgnetwork:
    driver: bridge

volumes:
  postgres-data-dev:
    driver: local
  redis-data-dev:
    driver: local
